// <auto-generated />
namespace NTTH1721050500.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_tale_Pe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tale_Pe));
        
        string IMigrationMetadata.Id
        {
            get { return "202110260716537_create_tale_Pe "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
